AWSTemplateFormatVersion: 2010-09-09
Description: 'Security Groups'

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]
  VPCId:
    Type: String

Resources:
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub 'web-alb-sg-${Environment}'
      GroupDescription: Security group for ALB
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub 'web-alb-sg-${Environment}'

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub 'web-ec2-sg-${Environment}'
      GroupDescription: Security group for EC2 instance
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub 'web-ec2-sg-${Environment}'

Outputs:
  ALBSecurityGroupId:
    Value: !Ref ALBSecurityGroup
  EC2SecurityGroupId:
    Value: !Ref EC2SecurityGroup